# Safety configuration for dependency vulnerability scanning
# https://docs.safetycli.com/

security:
  # Ignore specific vulnerabilities (with justification)
  ignore-vulnerabilities:
    # Example: Ignore vulnerability in development-only dependency
    # - id: "44715"
    #   reason: "This affects only development environment and is mitigated"
    #   expires: "2024-12-31"

  # Continue on vulnerability errors (don't fail CI)
  continue-on-vulnerability-error: false

  # Ignore unpinned requirements
  ignore-unpinned-requirements: false

  # Full reports include fix recommendations
  full-report: true

  # Auto-install security updates (use with caution)
  auto-security-updates: false

# Audit configuration
audit:
  # Ignore specific audit findings
  ignore-audit:
    # - id: "abc123"
    #   reason: "False positive - not exploitable in our context"
    #   expires: "2024-12-31"

  # Fail CI on any audit findings
  fail-security-audit: true

# Reporting configuration  
report:
  # Format: json, text, bare, full-report
  format: "json"
  
  # Output file for reports
  output: "safety-report.json"
  
  # Include full details
  full-report: true

# Policy enforcement
policy:
  # Maximum CVSS score allowed (0.0 - 10.0)
  max-cvss-score: 7.0
  
  # Minimum severity level (low, medium, high, critical)
  min-severity: "medium"
  
  # Fail on any findings above thresholds
  fail-on-findings: true

# Notification settings
notifications:
  # Slack webhook for critical findings
  slack:
    enabled: false
    webhook-url: "${SLACK_WEBHOOK_URL}"
    channel: "#security"
    
  # Email notifications
  email:
    enabled: false
    recipients:
      - "security@company.com"
